-- ============================================================
-- Watanare Reader - New Supabase Database Setup Script
-- Run this in the SQL Editor of your new Supabase project
-- ============================================================

-- 1. ENABLE REQUIRED EXTENSIONS
-- (uuid-ossp is usually enabled by default, but we ensure it)
extension if not exists "uuid-ossp";

-- 2. CREATE PROFILES TABLE
-- Stores public user profile data linked to auth.users
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text,
  avatar_url text,
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

comment on table public.profiles is 'Public profile data for each user.';

-- 3. CREATE GUESTBOOK TABLE
-- Stores anonymous/public guestbook entries
create table if not exists public.guestbook (
  id bigint generated by default as identity primary key,
  name text not null default 'Anonymous',
  message text not null,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

comment on table public.guestbook is 'Guestbook entries left by visitors.';

-- 4. CREATE COMMENTS TABLE
-- Stores nested chapter comments
create table if not exists public.comments (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users on delete cascade not null,
  volume_id text not null,
  chapter_title text not null,
  content text not null,
  parent_id uuid references public.comments(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

comment on table public.comments is 'Nested comments on book chapters.';

-- 5. CREATE COMMENT_REACTIONS TABLE
-- Stores upvotes/downvotes on comments
create table if not exists public.comment_reactions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  comment_id uuid references public.comments(id) on delete cascade not null,
  reaction_type text not null check (reaction_type in ('upvote', 'downvote')),
  created_at timestamp with time zone default timezone('utc'::text, now()),
  unique (user_id, comment_id)
);

comment on table public.comment_reactions is 'Upvotes and downvotes on comments.';

-- 6. CREATE READING_PROGRESS TABLE
-- Stores user's last read position per volume
create table if not exists public.reading_progress (
  user_id uuid references auth.users on delete cascade not null,
  volume_id text not null,
  chapter_index integer not null default 0,
  scroll_percentage integer not null default 0,
  last_read timestamp with time zone default timezone('utc'::text, now()),
  percentage integer not null default 0,
  primary key (user_id, volume_id)
);

comment on table public.reading_progress is 'Tracks user reading progress per volume.';

-- ============================================================
-- ENABLE ROW LEVEL SECURITY (RLS)
-- ============================================================

alter table public.profiles enable row level security;
alter table public.guestbook enable row level security;
alter table public.comments enable row level security;
alter table public.comment_reactions enable row level security;
alter table public.reading_progress enable row level security;

-- ============================================================
-- RLS POLICIES FOR PROFILES
-- ============================================================

-- Anyone can read profiles
create policy "Profiles are viewable by everyone"
  on public.profiles
  for select
  using (true);

-- Users can insert their own profile
create policy "Users can insert their own profile"
  on public.profiles
  for insert
  with check (auth.uid() = id);

-- Users can update their own profile
create policy "Users can update their own profile"
  on public.profiles
  for update
  using (auth.uid() = id);

-- ============================================================
-- RLS POLICIES FOR GUESTBOOK
-- ============================================================

-- Anyone can read guestbook entries
create policy "Guestbook entries are viewable by everyone"
  on public.guestbook
  for select
  using (true);

-- Anyone can insert guestbook entries (anonymous/public)
create policy "Anyone can insert guestbook entries"
  on public.guestbook
  for insert
  with check (true);

-- No updates/deletes needed for guestbook (or add admin policy later)

-- ============================================================
-- RLS POLICIES FOR COMMENTS
-- ============================================================

-- Anyone can read comments
create policy "Comments are viewable by everyone"
  on public.comments
  for select
  using (true);

-- Authenticated users can create comments
create policy "Authenticated users can create comments"
  on public.comments
  for insert
  with check (auth.uid() = user_id);

-- Users can delete their own comments
create policy "Users can delete their own comments"
  on public.comments
  for delete
  using (auth.uid() = user_id);

-- Users can update their own comments (optional, app may not use it)
create policy "Users can update their own comments"
  on public.comments
  for update
  using (auth.uid() = user_id);

-- ============================================================
-- RLS POLICIES FOR COMMENT_REACTIONS
-- ============================================================

-- Anyone can read reactions
create policy "Reactions are viewable by everyone"
  on public.comment_reactions
  for select
  using (true);

-- Authenticated users can insert their own reactions
create policy "Users can insert their own reactions"
  on public.comment_reactions
  for insert
  with check (auth.uid() = user_id);

-- Users can update their own reactions
create policy "Users can update their own reactions"
  on public.comment_reactions
  for update
  using (auth.uid() = user_id);

-- Users can delete their own reactions
create policy "Users can delete their own reactions"
  on public.comment_reactions
  for delete
  using (auth.uid() = user_id);

-- ============================================================
-- RLS POLICIES FOR READING_PROGRESS
-- ============================================================

-- Users can only read their own progress
create policy "Users can read their own progress"
  on public.reading_progress
  for select
  using (auth.uid() = user_id);

-- Users can insert their own progress
create policy "Users can insert their own progress"
  on public.reading_progress
  for insert
  with check (auth.uid() = user_id);

-- Users can update their own progress
create policy "Users can update their own progress"
  on public.reading_progress
  for update
  using (auth.uid() = user_id);

-- Users can delete their own progress
create policy "Users can delete their own progress"
  on public.reading_progress
  for delete
  using (auth.uid() = user_id);

-- ============================================================
-- CREATE REALTIME PUBLICATIONS
-- The app subscribes to realtime changes on comments and reactions
-- ============================================================

-- Drop existing if re-running
drop publication if exists supabase_realtime;

-- Create new publication for all tables
create publication supabase_realtime for table public.comments, public.comment_reactions;

-- ============================================================
-- CREATE DELETE_USER RPC FUNCTION
-- Called when a user deletes their account via ProfileModal
-- ============================================================

create or replace function public.delete_user()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Delete user's reading progress
  delete from public.reading_progress where user_id = auth.uid();
  
  -- Delete user's comment reactions
  delete from public.comment_reactions where user_id = auth.uid();
  
  -- Delete user's comments
  delete from public.comments where user_id = auth.uid();
  
  -- Delete user's profile
  delete from public.profiles where id = auth.uid();
  
  -- Delete the auth user (this requires service role or admin)
  -- In standard Supabase, users cannot delete themselves via RLS.
  -- We call this via supabase.auth.admin.deleteUser() on server,
  -- or we rely on the app calling auth admin API.
  -- For client-side deletion, we handle it differently.
  -- 
  -- NOTE: The current app calls supabase.rpc('delete_user').
  -- If the user is not an admin, the auth.users deletion will fail.
  -- You should handle account deletion via a Supabase Edge Function
  -- or manually from the Supabase Dashboard.
  --
  -- Uncomment below ONLY if running as service role / in Edge Function:
  -- delete from auth.users where id = auth.uid();
end;
$$;

-- Allow authenticated users to execute this function
create policy "Authenticated users can execute delete_user"
  on public.profiles
  for all
  using (auth.uid() = id);

-- ============================================================
-- CREATE HANDLE_NEW_USER TRIGGER
-- Automatically creates a profile row when a new user signs up
-- via email/password or OAuth. This ensures OAuth users also have profiles.
-- ============================================================

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username, avatar_url, updated_at)
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data->>'username',
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      split_part(new.email, '@', 1)
    ),
    new.raw_user_meta_data->>'avatar_url',
    timezone('utc'::text, now())
  );
  return new;
end;
$$;

-- Drop trigger if exists so script can be re-run
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================
-- STORAGE BUCKET SETUP
-- The app uses an 'avatars' bucket for profile picture uploads.
-- Run these in the Supabase Dashboard SQL Editor, or create
-- the bucket manually in Storage > New bucket.
-- ============================================================

-- NOTE: Storage buckets cannot be created purely via standard SQL.
-- Please create the 'avatars' bucket manually in your Supabase Dashboard:
--
-- 1. Go to Storage in the left sidebar
-- 2. Click "New bucket"
-- 3. Name it: avatars
-- 4. Set it to Public (the app generates public URLs via getPublicUrl)
-- 5. Enable RLS policies for the bucket (see below)
--
-- After creating the bucket, run the following policies via the Dashboard
-- or via the Supabase CLI (not standard PostgreSQL):
--
-- Policy 1: Allow authenticated users to upload to avatars
--    CREATE POLICY "Allow authenticated uploads" ON storage.objects
--    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'avatars');
--
-- Policy 2: Allow anyone to read avatars
--    CREATE POLICY "Allow public reads" ON storage.objects
--    FOR SELECT USING (bucket_id = 'avatars');
--
-- Policy 3: Allow authenticated users to update their own avatars
--    CREATE POLICY "Allow authenticated updates" ON storage.objects
--    FOR UPDATE TO authenticated USING (bucket_id = 'avatars' AND owner = auth.uid());
--
-- Policy 4: Allow authenticated users to delete their own avatars
--    CREATE POLICY "Allow authenticated deletes" ON storage.objects
--    FOR DELETE TO authenticated USING (bucket_id = 'avatars' AND owner = auth.uid());

-- ============================================================
-- AUTH CONFIGURATION (MANUAL STEPS IN DASHBOARD)
-- ============================================================

-- 1. Go to Authentication > Providers in Supabase Dashboard
-- 2. Enable "Email" provider (it is enabled by default)
--    - Disable "Confirm email" if you want immediate sign-in without verification
--      (or keep it enabled if you want email verification flow)
-- 3. Enable "Google" OAuth provider:
--    - You need a Google Cloud project and OAuth 2.0 credentials
--    - Add your Client ID and Secret in the Dashboard
--    - Set the Authorized Redirect URI to:
--      https://<your-project-ref>.supabase.co/auth/v1/callback
-- 4. Enable "GitHub" OAuth provider:
--    - You need a GitHub OAuth App
--    - Add your Client ID and Secret in the Dashboard
--    - Set the Authorization Callback URL to:
--      https://<your-project-ref>.supabase.co/auth/v1/callback
-- 5. In Authentication > URL Configuration, set:
--    - Site URL: https://your-domain.com (or http://localhost:3000 for dev)
--    - Redirect URLs: add any additional redirect URLs you need

-- ============================================================
-- DONE! Your database schema is ready.
-- ============================================================
